[workspace]
resolver = "2"
members = [
    "rep_system",
    "shared",
    "mark3t_rep"
]


[workspace.package]
version = "0.1.0"
authors = ["Parity Technologies"]
edition = "2024"

[workspace.dependencies]
ink = { version = "6.0.0-beta.1", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"] }
ink_e2e = { version = "6.0.0-beta.1" }


